services:
  web:
    build: .
    volumes:
      - ./app:/code/app
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 3 sec"
          sleep 3 
          uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ENDPOINT=mysql+pymysql://user:password@db/db
      - MYSQL_TEST_ENDPOINT=mysql+pymysql://user:password@db/test_db
    depends_on:
      - db
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  my-db:
